In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
from imblearn.over_sampling import RandomOverSampler, SMOTE
from imblearn.under_sampling import RandomUnderSampler, NearMiss

In [3]:
df_train = pd.read_csv("treino.csv")
df_test = pd.read_csv("teste.csv")

In [4]:
df_train.head(4)

inadimplente  util_linhas_inseguras  idade  vezes_passou_de_30_59_dias  \
0             1               0.766127     45                           2   
1             0               0.957151     40                           0   
2             0               0.658180     38                           1   
3             0               0.233810     30                           0   

   razao_debito  salario_mensal  numero_linhas_crdto_aberto  \
0      0.802982          9120.0                          13   
1      0.121876          2600.0                           4   
2      0.085113          3042.0                           2   
3      0.036050          3300.0                           5   

   numero_vezes_passou_90_dias  numero_emprestimos_imobiliarios  \
0                            0                                6   
1                            0                                0   
2                            1                                0   
3                            0                                0   

   numero_de_vezes_que_passou_60_89_dias  numero_de_dependentes  
0                                      0                    2.0  
1                                      0                    1.0  
2                                      0                    0.0  
3                                      0                    0.0

In [5]:
df_test.head(4)

util_linhas_inseguras  idade  vezes_passou_de_30_59_dias  razao_debito  \
0               0.025849     62                           0      0.081775   
1               0.667083     55                           0      0.153112   
2               0.007093     44                           0      0.148800   
3               0.091213     54                           0      0.351635   

   salario_mensal  numero_linhas_crdto_aberto  numero_vezes_passou_90_dias  \
0          8180.0                           3                            0   
1          2200.0                           3                            0   
2          7499.0                          20                            0   
3          5900.0                          15                            0   

   numero_emprestimos_imobiliarios  numero_de_vezes_que_passou_60_89_dias  \
0                                2                                      0   
1                                0                                      0   
2                                1                                      0   
3                                1                                      1   

   numero_de_dependentes  
0                    0.0  
1                    0.0  
2                    0.0  
3                    0.0

In [6]:
len(df_train)

110000

In [7]:
len(df_test)

40000

In [8]:
df = df_train

In [9]:
df.columns

Index(['inadimplente', 'util_linhas_inseguras', 'idade',
       'vezes_passou_de_30_59_dias', 'razao_debito', 'salario_mensal',
       'numero_linhas_crdto_aberto', 'numero_vezes_passou_90_dias',
       'numero_emprestimos_imobiliarios',
       'numero_de_vezes_que_passou_60_89_dias', 'numero_de_dependentes'],
      dtype='object')

In [10]:
df.describe()

inadimplente  util_linhas_inseguras          idade  \
count  110000.000000          110000.000000  110000.000000   
mean        0.066645               5.929979      52.255636   
std         0.249408             252.301965      14.768241   
min         0.000000               0.000000       0.000000   
25%         0.000000               0.030054      41.000000   
50%         0.000000               0.155936      52.000000   
75%         0.000000               0.562806      63.000000   
max         1.000000           50708.000000     109.000000   

       vezes_passou_de_30_59_dias   razao_debito  salario_mensal  \
count               110000.000000  110000.000000    8.823700e+04   
mean                     0.424055     354.823589    6.637411e+03   
std                      4.240780    2074.140421    1.338395e+04   
min                      0.000000       0.000000    0.000000e+00   
25%                      0.000000       0.175016    3.400000e+03   
50%                      0.000000       0.366682    5.400000e+03   
75%                      0.000000       0.866874    8.225000e+03   
max                     98.000000  329664.000000    3.008750e+06   

       numero_linhas_crdto_aberto  numero_vezes_passou_90_dias  \
count               110000.000000                110000.000000   
mean                     8.445573                     0.269955   
std                      5.139026                     4.217326   
min                      0.000000                     0.000000   
25%                      5.000000                     0.000000   
50%                      8.000000                     0.000000   
75%                     11.000000                     0.000000   
max                     58.000000                    98.000000   

       numero_emprestimos_imobiliarios  numero_de_vezes_que_passou_60_89_dias  \
count                    110000.000000                          110000.000000   
mean                          1.019891                               0.243891   
std                           1.135989                               4.204137   
min                           0.000000                               0.000000   
25%                           0.000000                               0.000000   
50%                           1.000000                               0.000000   
75%                           2.000000                               0.000000   
max                          54.000000                              98.000000   

       numero_de_dependentes  
count          107122.000000  
mean                0.757482  
std                 1.114670  
min                 0.000000  
25%                 0.000000  
50%                 0.000000  
75%                 1.000000  
max                20.000000

In [11]:
df.isnull().sum()

inadimplente                                 0
util_linhas_inseguras                        0
idade                                        0
vezes_passou_de_30_59_dias                   0
razao_debito                                 0
salario_mensal                           21763
numero_linhas_crdto_aberto                   0
numero_vezes_passou_90_dias                  0
numero_emprestimos_imobiliarios              0
numero_de_vezes_que_passou_60_89_dias        0
numero_de_dependentes                     2878
dtype: int64

In [12]:
df ['numero_de_dependentes'] = df ['numero_de_dependentes']. fillna (0)
df ['salario_mensal'] = df ['salario_mensal']. fillna (0)

In [13]:
df.isnull().sum()

inadimplente                             0
util_linhas_inseguras                    0
idade                                    0
vezes_passou_de_30_59_dias               0
razao_debito                             0
salario_mensal                           0
numero_linhas_crdto_aberto               0
numero_vezes_passou_90_dias              0
numero_emprestimos_imobiliarios          0
numero_de_vezes_que_passou_60_89_dias    0
numero_de_dependentes                    0
dtype: int64

In [14]:
target = np.unique(df['inadimplente'], return_counts = True) 

In [15]:
target

(array([0, 1]), array([102669,   7331]))

In [16]:
target[1][1]/target[1][0]

0.07140422133263205

In [17]:
np.unique(df['util_linhas_inseguras'], return_counts = True)

(array([0.0000e+00, 9.9300e-06, 1.4900e-05, ..., 2.2198e+04, 2.9110e+04,
        5.0708e+04]),
 array([7983,    1,    1, ...,    1,    1,    1]))

In [18]:
np.unique(df['idade'], return_counts = True)

(array([  0,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
         46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,
         59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
         72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 101, 102, 103, 105, 107, 109]),
 array([   1,  142,  324,  469,  616,  704,  874,  969, 1152, 1296, 1385,
        1475, 1504, 1681, 1600, 1647, 1733, 1837, 1926, 2242, 2282, 2265,
        2268, 2364, 2449, 2525, 2759, 2718, 2794, 2788, 2709, 2665, 2642,
        2660, 2640, 2526, 2602, 2485, 2555, 2418, 2350, 2585, 2599, 2705,
        2252, 1906, 1835, 1811, 1617, 1450, 1314, 1208, 1218, 1127, 1062,
         906,  873,  794,  758,  723,  612,  592,  471,  371,  347,  358,
         306,  253,  219,  197,  136,  108,   66,   71,   30,   34, 

In [19]:
np.unique(df['vezes_passou_de_30_59_dias'], return_counts = True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 13, 96, 98]),
 array([92469, 11726,  3343,  1304,   541,   246,    98,    41,    17,
            8,     2,     2,     1,     4,   198]))

In [20]:
np.unique(df['numero_linhas_crdto_aberto'], return_counts = True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 54, 56, 57, 58]),
 array([1419, 3252, 4915, 6652, 8512, 9521, 9988, 9675, 9171, 8240, 7095,
        6107, 5122, 4163, 3373, 2661, 2173, 1738, 1428, 1037,  847,  649,
         522,  394,  313,  221,  164,  138,  111,   91,   62,   58,   37,
          31,   21,   13,   17,    5,   11,    3,    8,    3,    4,    4,
           2,    5,    3,    1,    5,    2,    1,    2,    2,    4,    2,
           1,    1]))

In [21]:
np.unique(df['numero_vezes_passou_90_dias'], return_counts = True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 14, 15, 17, 96,
        98]),
 array([103836,   3886,   1160,    486,    204,    103,     58,     21,
            16,     15,      6,      2,      2,      1,      1,      1,
             4,    198]))

In [22]:
np.unique(df['numero_emprestimos_imobiliarios'], return_counts = True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 23, 25, 26, 29, 32, 54]),
 array([41159, 38354, 23161,  4644,  1601,   496,   237,   126,    67,
           58,    29,    15,    10,    13,     6,     5,     3,     4,
            1,     1,     1,     1,     2,     2,     1,     1,     1,
            1]))

In [23]:
np.unique(df['numero_de_vezes_que_passou_60_89_dias'], return_counts = True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 96, 98]),
 array([104466,   4169,    825,    222,     67,     26,     12,      7,
             2,      1,      1,      4,    198]))

In [24]:
np.unique(df['numero_de_dependentes'], return_counts = True)

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 20.]),
 array([66530, 19416, 14306,  6898,  2111,   563,   115,    38,    16,
            2,     4,     1]))

______________________________________

# ÁREA RESERVADA PARA ANÁLISE DE DADOS MATPLOTLIB

____

# ÁREA RESERVADA PARA PRE-PROCESSING

In [25]:
df.sample(3)

inadimplente  util_linhas_inseguras  idade  vezes_passou_de_30_59_dias  \
15228             0               0.843859     37                           0   
16330             0               0.602920     44                           0   
72938             1               0.085097     63                           1   

       razao_debito  salario_mensal  numero_linhas_crdto_aberto  \
15228   2746.000000             0.0                           6   
16330      0.591527          1250.0                           2   
72938      0.224155          5000.0                          18   

       numero_vezes_passou_90_dias  numero_emprestimos_imobiliarios  \
15228                            0                                3   
16330                            0                                0   
72938                            1                                0   

       numero_de_vezes_que_passou_60_89_dias  numero_de_dependentes  
15228                                      0                    0.0  
16330                                      0                    3.0  
72938                                      1                    1.0

In [26]:
df_target = df[['inadimplente']]

In [27]:
df_target.sample(4)

inadimplente
87988             0
65030             0
28837             0
90620             0

In [28]:
df = df.drop(['inadimplente'], axis = True)

In [29]:
df.columns

Index(['util_linhas_inseguras', 'idade', 'vezes_passou_de_30_59_dias',
       'razao_debito', 'salario_mensal', 'numero_linhas_crdto_aberto',
       'numero_vezes_passou_90_dias', 'numero_emprestimos_imobiliarios',
       'numero_de_vezes_que_passou_60_89_dias', 'numero_de_dependentes'],
      dtype='object')

In [30]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [31]:
min_max_scaler = preprocessing.MinMaxScaler()

In [32]:
x = df
y = df_target
x = min_max_scaler.fit_transform(x)

In [33]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(x)
x = scaler.transform(x)

In [34]:
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.under_sampling import RandomUnderSampler 
x_new, y_new = make_classification(n_classes=2, class_sep=2,

weights=[0.5, 0.5], n_informative=3, n_redundant=1, flip_y=0,

n_features=20, n_clusters_per_class=1, n_samples=60000, random_state=10)
print('Original dataset shape %s' % Counter(y))
rus = RandomUnderSampler(random_state=42)
print('Resampled dataset shape %s' % Counter(y_new))

Original dataset shape Counter({'inadimplente': 1})
Resampled dataset shape Counter({1: 30000, 0: 30000})


In [35]:
x_train, x_test, y_train, y_test = train_test_split(x_new, y_new, test_size = 0.20)

In [36]:
len(y_train)

48000

In [37]:
y_train.sum()

23981

In [38]:
len(y_train)

48000

In [39]:
y_train.sum()

23981

In [40]:
2*y_train.sum()

47962

In [41]:
from sklearn.datasets import make_classification
from sklearn import svm

In [42]:
clf = svm.SVC()

In [43]:
clf.fit(x_train, y_train)

SVC()

In [44]:
y_pred = clf.predict(x_test)

In [45]:
accuracy_score(y_test, y_pred)

0.9821666666666666

In [46]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[5815  166]
 [  48 5971]]
              precision    recall  f1-score   support

           0       0.99      0.97      0.98      5981
           1       0.97      0.99      0.98      6019

    accuracy                           0.98     12000
   macro avg       0.98      0.98      0.98     12000
weighted avg       0.98      0.98      0.98     12000



In [47]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(x_train, y_train)

SVC(kernel='sigmoid')

In [48]:
y_pred = svclassifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[5584  397]
 [ 431 5588]]
              precision    recall  f1-score   support

           0       0.93      0.93      0.93      5981
           1       0.93      0.93      0.93      6019

    accuracy                           0.93     12000
   macro avg       0.93      0.93      0.93     12000
weighted avg       0.93      0.93      0.93     12000



In [49]:
accuracy_score(y_test, y_pred)

0.931

In [50]:
df_test.head(4)

util_linhas_inseguras  idade  vezes_passou_de_30_59_dias  razao_debito  \
0               0.025849     62                           0      0.081775   
1               0.667083     55                           0      0.153112   
2               0.007093     44                           0      0.148800   
3               0.091213     54                           0      0.351635   

   salario_mensal  numero_linhas_crdto_aberto  numero_vezes_passou_90_dias  \
0          8180.0                           3                            0   
1          2200.0                           3                            0   
2          7499.0                          20                            0   
3          5900.0                          15                            0   

   numero_emprestimos_imobiliarios  numero_de_vezes_que_passou_60_89_dias  \
0                                2                                      0   
1                                0                                      0   
2                                1                                      0   
3                                1                                      1   

   numero_de_dependentes  
0                    0.0  
1                    0.0  
2                    0.0  
3                    0.0

In [51]:
# save the model to disk

In [52]:
filename = 'data_risk_model.sav'
pickle.dump(clf, open(filename, 'wb'))